### PR TITLE
license header fix for rat detection + exclusion of archetype content

### PR DESCRIPTION
**Pull request by ebarboni**
fix for rat compatibility.
exclusion of all the resources for archetype so the result is without license.

will later change the ci-build on jenkins to execute apache-rat:check.

### CODE REVIEW

**Comment by asbachb** [comment]
@ebarboni rat doesn't detect `https` versions of apache license url?

**Comment by neilcsmith-net** [comment]
@asbachb See eg. https://issues.apache.org/jira/browse/RAT-253

**Review by neilcsmith-net — APPROVED** [review]
@ebarboni I think this makes sense - treat archetype content as no creative content?

Incidentally, if we updated netbeans-parent to latest apache-parent, we shouldn't need to change the https license links! :wink:  Could update rat plugin?

**Comment by ebarboni** [comment]
but rat plugin 15 fail on https 

maybe we could add on parent the pluginmanagment for the utils + package ?

**Comment by neilcsmith-net** [comment]
> but rat plugin 15 fail on https

well, I didn't test, but according to the release notes it should work ... :shrug:

**Pull request merged**
